import { markdownToHtml } from '../src';
import { readFileSync, writeFileSync } from 'fs';

const cheatsheet = readFileSync('./playground/cheatsheet.md', 'utf-8');
const result = markdownToHtml(cheatsheet);
const html = `<!DOCTYPE html>
<html>
<head>
    <meta charset=\"utf-8\">
    <title>Markdown to HTML</title>
</head>
<body>
<!-- Generated by Markus -->
${result}
<!-- End Generated by Markus -->
</body>
</html>`;

writeFileSync('./playground/result.html', html, 'utf-8');
